### ISSUE TITLE
[Server] implement api to accept a client.post('/setDataFromClient') that accepts data and prints value

### ISSUE THREAD

**Issue by SwaroopAkkineni** [SwaroopAkkineni/financialFreedom#6]
For now, the client, when the button is pressed, is sending a body of 'test', to locahost:3000/setDataFromClient, on the server. Can you implement that in go on the server side

**Comment by FiscalTiger** [comment]
What do you want that path to do?

**Comment by FiscalTiger** [comment]
Talked offline, I am just taking the body of the request logging it

**Comment by FiscalTiger** [comment]
Just merged changes into mainline
